export const BLOG_POSTS = [
  {
    slug: "vendas-whatsapp-2026",
    image: "assets/img/blog/blog_2_1.jpg",
    date: "20 jan 2026",
    category: "Vendas",
    title: "Como aumentar suas vendas pelo WhatsApp em 2026",
    excerpt: "Estratégias práticas para converter mais conversas em negócios fechados.",
    href: "/blog-details",
  },
  {
    slug: "automacoes-comerciais",
    image: "assets/img/blog/blog_2_2.jpg",
    date: "22 jan 2026",
    category: "Automação",
    title: "5 automações que todo time comercial precisa",
    excerpt: "Fluxos que economizam horas e mantêm o follow-up em dia sem esforço manual.",
    href: "/blog-details",
  },
  {
    slug: "ia-no-atendimento",
    image: "assets/img/blog/blog_2_3.jpg",
    date: "23 jan 2026",
    category: "IA",
    title: "IA no atendimento: como implementar sem complicação",
    excerpt: "Passo a passo para usar IA na qualificação sem perder o toque humano.",
    href: "/blog-details",
  },
  {
    slug: "inbox-compartilhado",
    image: "assets/img/blog/blog_2_1.jpg",
    date: "28 jan 2026",
    category: "Operação",
    title: "Inbox compartilhado: fim do caos no WhatsApp do time",
    excerpt: "Como organizar filas, etiquetas e SLA quando vários atendentes usam o mesmo número.",
    href: "/blog-details",
  },
  {
    slug: "crm-kanban",
    image: "assets/img/blog/blog_2_2.jpg",
    date: "2 fev 2026",
    category: "CRM",
    title: "CRM Kanban no WhatsApp: funil visual que o time adota",
    excerpt: "Por que arrastar cards entre etapas funciona melhor que planilhas para times comerciais.",
    href: "/blog-details",
  },
  {
    slug: "integracao-erp",
    image: "assets/img/blog/blog_2_3.jpg",
    date: "5 fev 2026",
    category: "Integrações",
    title: "Integrando wChat com seu ERP em uma tarde",
    excerpt: "API, webhooks e N8N: opções para sincronizar pedidos, contatos e status de negociação.",
    href: "/blog-details",
  },
];
