export const CASE_STUDIES = [
  {
    image: "assets/img/service/service_3_1.jpg",
    tag: "Agente IA",
    title: "Qualificação automática de leads",
    text: "A IA responde no primeiro contato, coleta dados e encaminha só leads quentes para o vendedor — 24 horas por dia.",
    logo: "assets/img/icon/ser-logo1.png",
    delay: ".1s",
  },
  {
    image: "assets/img/service/service_3_2.jpg",
    tag: "CRM Kanban",
    title: "Funil visual no WhatsApp",
    text: "Arraste negociações entre etapas, acompanhe conversão e nunca perca um follow-up no meio do caminho.",
    logo: "assets/img/icon/ser-logo2.png",
    delay: ".3s",
  },
  {
    image: "assets/img/service/service_3_3.jpg",
    tag: "Inbox compartilhado",
    title: "Time inteiro, um número",
    text: "Filas, etiquetas e distribuição automática para que nenhum cliente fique sem resposta.",
    logo: "assets/img/icon/ser-logo3.png",
    delay: ".5s",
  },
  {
    image: "assets/img/service/service_3_1.jpg",
    tag: "Automações",
    title: "Campanhas e nutrição de leads",
    text: "Dispare sequências segmentadas, reative inativos e acompanhe resultados sem sair do wChat.",
    logo: "assets/img/icon/ser-logo1.png",
    delay: ".1s",
  },
  {
    image: "assets/img/service/service_3_2.jpg",
    tag: "Relatórios",
    title: "Dashboards em tempo real",
    text: "SLA, conversão por etapa e performance individual — tudo atualizado ao vivo para gestores.",
    logo: "assets/img/icon/ser-logo2.png",
    delay: ".3s",
  },
  {
    image: "assets/img/service/service_3_3.jpg",
    tag: "API",
    title: "Integração com ERP e CRM",
    text: "Sincronize negociações, contatos e eventos via REST, webhooks ou N8N.",
    logo: "assets/img/icon/ser-logo3.png",
    delay: ".5s",
  },
];
